drop table Summary
drop table ParticipantJourneyModality
drop table ModalityForm
drop table TemplateFieldValue
drop table TemplateTemplateField
drop table TemplateField
drop table Template
drop table Form
drop table EventModality
drop table Modality
drop table AuditLog
drop table Participant
drop table PreRegistration
drop table ReferenceRange
drop table StandardReference
drop table ReferenceRange
drop table ParticipantPHSEvent
drop table PHSEvent
drop table PHSUser
drop table SummaryMapping