//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpGroup
    {
        public int FollowUpGroupID { get; set; }
        public string Title { get; set; }
        public string Filter { get; set; }
        public int FollowUpConfigurationID { get; set; }
    
        public virtual FollowUpConfiguration FollowUpConfiguration { get; set; }
    }
}
