//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FollowUpGroup()
        {
            this.ParticipantCallerMappings = new HashSet<ParticipantCallerMapping>();
        }
    
        public int FollowUpGroupID { get; set; }
        public string Title { get; set; }
        public string Filter { get; set; }
        public string HealthReportType { get; set; }
        public Nullable<bool> PrintHealthReport { get; set; }
        public Nullable<bool> FreeConsultationEligible { get; set; }
        public Nullable<bool> TeleHealthEligible { get; set; }
        public string BuddyFormType { get; set; }
        public int FollowUpConfigurationID { get; set; }
    
        public virtual FollowUpConfiguration FollowUpConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantCallerMapping> ParticipantCallerMappings { get; set; }
    }
}
