//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FollowUpConfiguration()
        {
            this.FollowUpGroups = new HashSet<FollowUpGroup>();
        }
    
        public int FollowUpConfigurationID { get; set; }
        public string Title { get; set; }
        public Nullable<int> PHSEventID { get; set; }
        public bool Deploy { get; set; }
    
        public virtual PHSEvent PHSEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpGroup> FollowUpGroups { get; set; }
    }
}
