//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormFieldValue
    {
        public int ID { get; set; }
        public int FieldId { get; set; }
        public System.Guid EntryId { get; set; }
        public string Value { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual TemplateField FormField { get; set; }
    }
}
