//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterAddress
    {
        public string POSTAL_CODE { get; set; }
        public string BUILDING_NAME { get; set; }
        public string STREET_NUMBER { get; set; }
        public string STREET_NAME { get; set; }
    }
}
