//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalityForm
    {
        public int ModalityID { get; set; }
        public int FormID { get; set; }
    
        public virtual form form { get; set; }
        public virtual Modality Modality { get; set; }
    }
}
