//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modality()
        {
            this.ParticipantJourneyModalities = new HashSet<ParticipantJourneyModality>();
            this.Summaries = new HashSet<Summary>();
            this.PHSEvents = new HashSet<PHSEvent>();
            this.Forms = new HashSet<Form>();
        }
    
        public int ModalityID { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public string IconPath { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<bool> HasParent { get; set; }
        public string Status { get; set; }
        public string Eligiblity { get; set; }
        public Nullable<int> Labels { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantJourneyModality> ParticipantJourneyModalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary> Summaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHSEvent> PHSEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
    }
}
