//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantCallerMapping
    {
        public int ParticipantCallerMappingID { get; set; }
        public int ParticipantID { get; set; }
        public int FollowUpGroupID { get; set; }
        public string FollowUpVolunteer { get; set; }
        public string FollowUpVolunteerCallStatus { get; set; }
        public Nullable<System.DateTime> FollowUpVolunteerCallDateTime { get; set; }
        public string FollowUpVolunteerCallRemark { get; set; }
        public string CommitteeMember { get; set; }
        public string CommitteeMemberCallStatus { get; set; }
        public Nullable<System.DateTime> CommitteeMemberCallDateTime { get; set; }
        public string CommitteeMemberCallRemark { get; set; }
    
        public virtual FollowUpGroup FollowUpGroup { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
