//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantJourneyModality
    {
        public int ParticipantJourneyModalityID { get; set; }
        public int ParticipantID { get; set; }
        public int PHSEventID { get; set; }
        public int ModalityID { get; set; }
        public int FormID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public System.Guid EntryId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Modality Modality { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual PHSEvent PHSEvent { get; set; }
        public virtual Template Template { get; set; }
    }
}
