//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreRegistration
    {
        public int PreRegistrationID { get; set; }
        public string Nric { get; set; }
        public System.Guid EntryId { get; set; }
        public string FullName { get; set; }
        public string Salutation { get; set; }
        public string HomeNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string Race { get; set; }
        public string Language { get; set; }
        public string PreferedTime { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
