//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryMapping
    {
        public int SummaryMappingID { get; set; }
        public string SummaryType { get; set; }
        public string CategoryName { get; set; }
        public string SummaryFieldName { get; set; }
    }
}
