//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int SummaryID { get; set; }
        public string Label { get; set; }
        public int ParticipantID { get; set; }
        public int PHSEventID { get; set; }
        public int ModalityID { get; set; }
        public int TemplateFieldID { get; set; }
        public string SummaryLabel { get; set; }
        public string SummaryValue { get; set; }
        public string SummaryType { get; set; }
        public Nullable<int> StandardReferenceID { get; set; }
    
        public virtual Modality Modality { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual PHSEvent PHSEvent { get; set; }
        public virtual StandardReference StandardReference { get; set; }
        public virtual TemplateField TemplateField { get; set; }
    }
}
